version: "3.6"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.29
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    ports:
      - "14268:14268"
      - "16686:16686"
      - "9411:9411"
      - "6832:6832"
      - "6832:6832/udp"

  skywalking:
    image: apache/skywalking-oap-server:8.8.1
    environment:
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
      - SW_PROMETHEUS_FETCHER_ENABLED_RULES=self
      - SW_PROMETHEUS_FETCHER=default
    ports:
      - "12800:12800"
      - "11800:11800"
    volumes:
      - ./config/sw-node-exporter.yaml:/skywalking/config/fetcher-prom-rules/node-exporter.yaml
    depends_on:
      - elasticsearch

  skywalking-ui:
    image: apache/skywalking-ui:8.8.1
    ports:
      - "18080:8080"
    environment:
      - SW_OAP_ADDRESS=http://skywalking:12800
    depends_on:
      - skywalking

  etcd:
    image: bitnami/etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - ./data/etcd:/bitnami/etcd/data # 注意这个目录要0777，不然访问被限

  elasticsearch:
    image: elasticsearch:7.14.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.14.2
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"

  apisix:
    image: apache/apisix:2.10.2-centos
    volumes:
      - ./config/apisix.yaml:/usr/local/apisix/conf/config.yaml
    ports:
      - "9080:9080"
      - "9180:9180"
    depends_on:
      - etcd

  apisix-dashboard:
    image: apache/apisix-dashboard:2.9.0
    volumes:
      - ./config/apisix-dashboard.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "9081:9000"
    depends_on:
      - etcd
  
  whoami-a:
    image: containous/whoami
    ports:
      - "8081:80"
  whoami-b:
    image: containous/whoami
    ports:
      - "8083:80"
